# buildspec.yml
version: 0.2
env:
  variables:
    AWS_DEFAULT_REGION: ap-northeast-2
    AWS_ACCOUNT_ID: 289850138235
    BACKEND_ENDPOINT : $BACKEND_ENDPOINT
    BACKEND_ELB_ENDPOINT : $BACKEND_ELB_ENDPOINT
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - echo "REACT_APP_BACKEND_ENDPOINT = '$BACKEND_ENDPOINT'" > ./.env
      - cat ./.env
      - echo 'server {' >> ./nginx.conf
      - echo '    listen 80;' >> ./nginx.conf
      - echo '    server_name $BACKEND_ENDPOINT;' >> ./nginx.conf
      - echo '    location / {' >> ./nginx.conf
      - echo "        proxy_pass $BACKEND_ELB_ENDPOINT;" >> ./nginx.conf
      - echo '    }' >> ./nginx.conf
      - echo '}' >> ./nginx.conf
      - cat ./nginx.conf
  build:
    commands:
      - echo Build react app
      - npm install
      - npm run build
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t hwp:front .
      - docker tag hwp:front 289850138235.dkr.ecr.ap-northeast-2.amazonaws.com/hwp:front
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 289850138235.dkr.ecr.ap-northeast-2.amazonaws.com/hwp:front
artifacts:
  files:
    - appspec.yml
    - scripts/**
cache:
  paths:
    - node_modules/**/*
